version: '3.8'

volumes:
  image_data_source_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./examples/image_data_source
  image_data_processed_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./examples/image_data_processed
  json_data_source_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./examples/json_data_source
  json_data_processed_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./examples/json_data_processed

services:
  dagster:
    build:
      context: ./data_orchestrator.py
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./data_orchestrator.py/dagster_project/.env.test
    volumes:
      - image_data_source_volume:/mnt/image_data_source
      - image_data_processed_volume:/mnt/image_data_processed
      - json_data_source_volume:/mnt/json_data_source
      - json_data_processed_volume:/mnt/json_data_processed

  validation_tool:
    build:
      context: ./validation_tool.ts
      dockerfile: Dockerfile
    ports:
      - "7456:7456"
    volumes:
      - image_data_source_volume:/mnt/image_data_source
      - image_data_processed_volume:/mnt/image_data_processed
      - json_data_source_volume:/mnt/json_data_source
      - json_data_processed_volume:/mnt/json_data_processed