version: '3.8'

volumes:
  cards_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./examples/cards_to_process
  data_source_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./validation_tool.ts/data_source
  data_processed_batches_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./validation_tool.ts/data_processed_batches

services:
  dagster:
    build:
      context: ./data_orchestrator.py
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./data_orchestrator.py/dagster_project/.env.test
    volumes:
      - cards_data:/mnt/cards_to_process

  validation_tool:
    build:
      context: ./validation_tool.ts
      dockerfile: Dockerfile
    ports:
      - "7456:7456"
    volumes:
      - cards_data:/mnt/cards_to_process
      - data_source_volume:/mnt/data_source
      - data_processed_batches_volume:/mnt/data_processed_batches