# This is the main workflow that orchestrates the reusable workflows.
name: Monorepo CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  # This job calls the installation workflow.
  install:
    uses: ./.github/workflows/reusable-install.yml

  # This job calls the testing workflow and depends on the install job completing successfully.
  test:
    needs: install
    # Permissions are granted here and inherited by the reusable workflow.
    permissions:
      contents: read
      checks: write
      pull-requests: write
    uses: ./.github/workflows/reusable-test.yml
