name: Monorepo CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

# Add permissions required for the test reporter to post check runs and PR comments.
permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- Python (dagster_card_processor) Setup ---
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: "dagster_card_processor/requirements.txt"

      - name: Python | Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dagster_card_processor/requirements.txt

      # --- Node.js (validation_tool.ts) Setup ---
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          cache-dependency-path: "validation_tool.ts/pnpm-lock.yaml"

      - name: Node.js | Install dependencies
        run: pnpm install
        working-directory: ./validation_tool.ts

      # --- Linting and Testing Steps ---
      - name: Python | Lint with flake8
        working-directory: ./dagster_card_processor
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Python | Test with pytest
        id: python-tests
        working-directory: ./dagster_card_processor
        continue-on-error: true
        run: pytest --junitxml=pytest-report.xml

      - name: Node.js | Run build, lint, and tests
        id: node-tests
        working-directory: ./validation_tool.ts
        continue-on-error: true
        run: |
          pnpm build
          pnpm typecheck
          pnpm test

      # --- Test Reporting Step ---
      - name: Report test results
        if: success() || failure()
        uses: dorny/test-reporter@v1
        with:
          name: Test Results
          path: "dagster_card_processor/pytest-report.xml, validation_tool.ts/junit.xml"
          fail-on-error: true
