# This workflow's job is to install dependencies, cache them, and create artifacts for subsequent jobs.
name: Install Dependencies

on:
  workflow_call:

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- Python Setup & Caching ---
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache Python virtual environment
        id: cache-venv
        uses: actions/cache@v4
        with:
          path: ./.venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-

      - name: Install Python dependencies
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r dagster_card_processor/requirements.txt

      - name: Upload Python venv artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-venv
          path: ./.venv
          retention-days: 1

      # --- Node.js Setup & Caching ---
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Set up Node.js 20 and cache pnpm dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: validation_tool.ts/pnpm-lock.yaml

      - name: Node.js | Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: ./validation_tool.ts

      - name: Upload Node.js modules artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-modules
          path: ./validation_tool.ts/node_modules
          retention-days: 1
