# This workflow's only job is to install dependencies and cache them.
name: Install Dependencies

on:
  # This trigger allows the workflow to be called by other workflows.
  workflow_call:

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- Python Setup & Caching ---
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: "**/requirements.txt"

      - name: Python | Install dependencies
        run: pip install -r dagster_card_processor/requirements.txt

      # --- Node.js Setup & Caching ---
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Cache pnpm dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Node.js | Install dependencies
        run: pnpm install
        working-directory: ./validation_tool.ts
